"""
Evolutionary Loop Router

Endpoints:
  GET  /loop/status    — agent statuses (all agents)
  POST /loop/trigger   — manually trigger a generation cycle
  GET  /loop/history   — cycle history from DB
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from core.schemas import AgentStatus, CycleResult

router = APIRouter(tags=["loop"])


def _get_loop(request: Request):
    loop = getattr(request.app.state, "loop", None)
    if loop is None:
        raise HTTPException(status_code=503, detail="Quant engine not initialised")
    return loop


class TriggerRequest(BaseModel):
    topic: str = "momentum and mean-reversion hybrid strategy for crypto futures"


class SummarizeRequest(BaseModel):
    link: str
    force: bool = False


class ScoutSettingsRequest(BaseModel):
    model_name: str


@router.get("/status")
async def get_loop_status(request: Request) -> dict:
    """Return current status of all agents in the evolutionary loop."""
    loop = _get_loop(request)
    statuses = loop.get_status()
    return {
        "agents": {name: s.model_dump() for name, s in statuses.items()}
    }


@router.get("/logs")
async def get_loop_logs(request: Request) -> list[dict]:
    """Return the recent agent activity logs."""
    loop = _get_loop(request)
    return loop.get_logs()


@router.post("/trigger", response_model=CycleResult)
async def trigger_generation_cycle(body: TriggerRequest, request: Request) -> CycleResult:
    """Manually trigger a full generation cycle."""
    loop = _get_loop(request)
    result = await loop.run_generation_cycle(body.topic)
    return result


@router.post("/research/summarize")
async def summarize_research_item(body: SummarizeRequest, request: Request):
    """Analyze a single research item using ScoutAgent (Saved to DB)."""
    loop = _get_loop(request)
    summary = await loop.scout_agent.summarize_finding(body.link, force=body.force)
    return {"summary": summary}


class ArchiveRequest(BaseModel):
    link: str
    category: str = "scout_reports"

@router.post("/research/save-to-brain")
async def archive_to_brain(body: ArchiveRequest, request: Request):
    """Save a research finding and its summary as a Markdown file in research/ directory."""
    loop = _get_loop(request)
    
    # Get finding and source info from DB
    cursor = loop.db.execute(
        """
        SELECT f.title, f.description, f.ai_summary, f.timestamp, s.name as source_name 
        FROM research_findings f
        JOIN research_sources s ON f.source_id = s.id
        WHERE f.link = ?
        """, 
        (body.link,)
    )
    row = cursor.fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Finding not found in DB")
    
    title, description, summary, ts, source_name = row
    
    # Prepare filename: Use topic title (sanitized)
    from datetime import datetime
    safe_title = "".join(x for x in title if x.isalnum() or x in " -_").strip().replace(" ", "_")[:60]
    filename = f"{safe_title}.md"
    
    from pathlib import Path
    if not loop.scout_agent.research_dir:
        raise HTTPException(status_code=500, detail="Research directory not configured")
        
    target_path = Path(loop.scout_agent.research_dir) / filename
    # If file exists, add timestamp to avoid collision but keep title
    if target_path.exists():
        filename = f"{safe_title}_{datetime.now().strftime('%H%M%S')}.md"
        target_path = Path(loop.scout_agent.research_dir) / filename

    target_path.parent.mkdir(parents=True, exist_ok=True)
    
    md_content = f"""# {title}
*Archived from Scout Agent at {datetime.now().isoformat()}*

## Meta
- **Source:** {source_name}
- **Original Link:** {body.link}
- **Analysis Tags:** #scout #alpha #{source_name.replace(' ', '')}

## Project Description
{description}

## AI Analysis & Insights
{summary if summary else "No AI analysis performed yet."}

---
*Generated by Quant Intelligence Hub*
"""
    
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    return {"success": True, "filename": filename, "path": str(target_path)}


@router.get("/agents/scout_agent/settings")
async def get_scout_agent_settings(request: Request):
    """Get Scout Agent specific settings (LLM model)."""
    loop = _get_loop(request)
    return loop.scout_agent.get_settings()


@router.post("/agents/scout_agent/settings")
async def update_scout_agent_settings(body: ScoutSettingsRequest, request: Request):
    """Update Scout Agent specific settings (LLM model)."""
    loop = _get_loop(request)
    loop.scout_agent.update_settings(body.model_name)
    return {"success": True}


@router.post("/agents/{agent_name}/trigger")
async def trigger_individual_agent(agent_name: str, body: dict, request: Request):
    loop = _get_loop(request)
    if agent_name == "scout_agent":
        topic = await loop.scout_agent.scout_for_alpha()
        loop._add_log(f"Manual: ScoutAgent found topic: {topic}")
        return {"result": topic}
    elif agent_name == "scout_agent_scrape":
        source_id = body.get("source_id")
        findings = await loop.scout_agent.run_scrape_only(source_id=source_id)
        loop._add_log(f"Manual: ScoutAgent synced {len(findings)} ideas to DB from source {source_id or 'all'}")
        return {"findings": findings}
    elif agent_name == "alpha_agent":
        topic = body.get("topic", "auto")
        res = await loop.alpha_agent.generate_strategy(topic)
        return res
    elif agent_name == "sentiment_agent":
        await loop.sentiment_agent.compute_all()
        return {"status": "success"}
    elif agent_name == "data_agent":
        await loop.data_agent.run_etl_all()
        return {"status": "success"}
    elif agent_name == "decay_check":
        decayed = await loop.run_decay_check()
        return {"decayed_strategies": decayed}
    else:
        raise HTTPException(status_code=400, detail=f"Agent '{agent_name}' not triggerable")


@router.get("/history")
async def get_loop_history(request: Request) -> list[dict]:
    loop = _get_loop(request)
    cursor = loop.db.execute("SELECT cycle_id, started_at, completed_at, strategies_generated, strategies_approved, strategies_rejected, errors FROM cycle_history ORDER BY started_at DESC LIMIT 100")
    rows = cursor.fetchall()
    import json
    return [{"cycle_id": r[0], "started_at": r[1], "completed_at": r[2], "strategies_generated": r[3], "strategies_approved": r[4], "strategies_rejected": r[5], "errors": json.loads(r[6]) if r[6] else []} for r in rows]

# ─── Research Sources Endpoints ──────────────────────────────────────────────

class SourceCreateRequest(BaseModel):
    name: str
    type: str
    url: str
    config: dict = {}

class SourcePatchRequest(BaseModel):
    enabled: bool | None = None
    url: str | None = None
    config: dict | None = None

@router.get("/research-sources")
async def get_research_sources(request: Request):
    loop = _get_loop(request)
    return loop.scout_agent.get_sources()

@router.post("/research-sources")
async def add_research_source(body: SourceCreateRequest, request: Request):
    loop = _get_loop(request)
    source_id = loop.scout_agent.add_source(body.name, body.type, body.url, body.config)
    return {"id": source_id, "success": True}

@router.patch("/research-sources/{source_id}")
async def update_research_source(source_id: int, body: SourcePatchRequest, request: Request):
    loop = _get_loop(request)
    loop.scout_agent.update_source(source_id, enabled=body.enabled, url=body.url, config=body.config)
    return {"success": True}

@router.delete("/research-sources/{source_id}")
async def delete_research_source(source_id: int, request: Request):
    loop = _get_loop(request)
    loop.scout_agent.delete_source(source_id)
    return {"success": True}
